title: Yi-Ming Li(Leo)
# subtitle: Resume
url: "https://LeoYimingLi.github.io"
# url: "https://ankitsultana.com"
# baseurl: "/researcher"
remote_theme: ankitsultana/researcher@gem

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.google.com/"
# footer_text: "Page design by Ankit Sultana"
footer_text: ""

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Transcripts"
   link: "Transcripts.pdf"
 - name: "Resume"
   link: "CV.pdf"
 - name: "IELTS"
   link: "English Proficiency.pdf"
